version: '3'

#might need: sudo apt-get install mysql-server

services:

#### from weight team ### 
  weight_be:
    container_name: weight_be
    build: 
      context: ./weight/weight_be
      dockerfile: Dockerfile.gunicorn
      args: 
        - DB_HOST='weight_db'
        - BD_PORT='3306'
        - DB_DB='weight'
        - DB_USER='dodo'
        - DB_PW='1111'
    ports: 
      - "8090:8090"
    restart: always
    networks: 
      - weight_net

  db:
    container_name: weight_db
    build: 
      context: ./weight/weight_database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "db_save:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: 'weight'
      MYSQL_USER: 'dodo'
      MYSQL_PASSWORD: '1111'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1111'
    # ports:
    #   # <Port exposed> : < MySQL Port running inside container>
    #   - '3400:3400'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks: 
      - weight_net


### from providers team ###
  providers:
    container_name: providers
    build: 
        context: ./providers
        dockerfile: Dockerfile

### Shared by both teams. 
volumes: 
  db_save: #weight

networks: 
  weight_net: #weight


