FROM python:3.6.9-alpine3.10

COPY requirements.txt /app/

WORKDIR /app

RUN pip3 install -r requirements.txt 


COPY weights/ /app/weights/

# RUN env FLASK_APP="weights:create_app()" flask init-db


# ENTRYPOINT [ "gunicorn", "--bind=:8090", "weights:create_app()" ]
ENTRYPOINT [ "env", "FLASK_APP='weights:create_app()'", "flask", "run", "--port", "8090"  ] 


