FROM python:3.8-alpine

#COPY requirements.txt /app/

WORKDIR /app

COPY ./requirements-test.txt . 

RUN pip install --upgrade pip
RUN pip3 install -r requirements-test.txt 

COPY test_health-test.py /app/

ENTRYPOINT ["python3", "test_health-test.py"]
