version: '3'

### USED FOR TESTING IN THE CI SERVER!!! 

#might need: sudo apt-get install mysql-server

services:
  weight_be_test:
    container_name: weight_be_test
    build: 
      context: ./weight_be
      dockerfile: Dockerfile.gunicorn
      args: 
        - DB_HOST='weight_db'
        - BD_PORT='3306'
        - DB_DB='weight'
        - DB_USER='dodo'
        - DB_PW='1111'
    ports: 
      - "8089:8090"
    restart: always
    networks: 
      - weight_net_test

  weight_db_test:
    container_name: weight_db_test
    build: 
      context: ./weight_database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "db_save:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: 'weight'
      MYSQL_USER: 'dodo'
      MYSQL_PASSWORD: '1111'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1111'
    # ports:
    #   # <Port exposed> : < MySQL Port running inside container>
    #   - '3400:3400'
    ###expose:
      # Opens port 3306 on the container
    ###  - '3306'
      # Where our data will be persisted
    networks: 
      - weight_net_test

  weight_tests:
    container_name: weight_tests
    build: 
      context: ./weight_tests
      dockerfile: Dockerfile
    networks: 
      - weight_net_test

volumes: 
  db_save:

networks: 
  weight_net_test:


