version: '3'

#might need: sudo apt-get install mysql-server

services:
  weight_be:
    container_name: weight_be
    build: 
      context: ./weight_be
      dockerfile: Dockerfile.gunicorn
    ports: 
      - "8090:8090"
    restart: always

  db:
    container_name: weight_db
    build: 
      context: ./weight_database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "db_save:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: 'weight'
      MYSQL_USER: 'dodo'
      MYSQL_PASSWORD: '1111'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1111'
    # ports:
    #   # <Port exposed> : < MySQL Port running inside container>
    #   - '3400:3400'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
volumes: 
  db_save:

