version: "3"
services:
  app:
    build:
      context: ./weight_be
      dockerfile: Dockerfile.gunicorn
    links:
      - db
    ports:
      - "8090:8090"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro